version: 2.1

jobs:
  check:
    working_directory: ~/app/
    docker:
      - image: cimg/python:3.14

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "uv.lock" }}
      - run:
          name: Upgrade uv
          command: |
            pip install uv -U
      - run:
          name: install dependencies
          command: |
            uv sync
      - save_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "uv.lock" }}
          paths:
            - "/home/circleci/.aws"
            - "/home/circlci/.local"
            - "/usr/local/bin"

      - run:
          name: code checks (ruff)
          command: |
            uv run poe check

  test:
    working_directory: ~/app/
    docker:
      - image: cimg/python:3.14

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - restore_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "uv.lock" }}
      - run:
          name: Upgrade uv
          command: |
            pip install uv -U
      - run:
          name: install dependencies
          command: |
            uv sync
      - save_cache:
          key: deps-v1-{{ .Branch }}-{{ checksum "uv.lock" }}
          paths:
            - "/home/circleci/.aws"
            - "/home/circlci/.local"
            - "/usr/local/bin"

      - run:
          name: run tests
          command: |

            uv run poe test

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

  build-package:
    working_directory: ~/app/
    docker:
      - image: cimg/python:3.14

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run:
          name: prepare boto3 credentials and awscli (Set via ENVARS[AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY])
          command: |
            # create ~/.aws/config
            echo "Creating: ~/.aws/config"
            mkdir -p ~/.aws
            cat \<<EOT > ~/.aws/config
            [default]
            region = ${AWS_DEFAULT_REGION}
            output = json

            [profile ${AWS_PROFILE}]
            role_arn = ${AWS_ROLE_ARN}
            region = ${AWS_DEFAULT_REGION}
            source_profile = default
            EOT

            # create .aws/credentials
            echo "Creating: ~/.aws/credentials"
            cat \<<EOT > ~/.aws/credentials
            [default]
            aws_access_key_id = ${AWS_ACCESS_KEY_ID}
            aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
            EOT

      - restore_cache:
          key: deps-v1-{{ .Branch }}-deploy-{{ checksum "uv.lock" }}
      - run:
          name: Upgrade pip & uv & install boto3
          command: |
            pip install pip -U
            pip install uv -U
            pip install boto3
      - run:
          name: install locked dependencies
          environment:
            PIP_NO_BINARY: pydantic
          command: |
            uv sync --no-dev
      - save_cache:
          key: deps-v1-{{ .Branch }}-deploy-{{ checksum "uv.lock" }}
          paths:
            - "/home/circleci/.aws"
            - "/home/circleci/.profile"
            - "/home/circleci/.local"
            - "/usr/local/bin"

      - run:
          name: build package
          command: | 
            cd ~/app
            mkdir -p ~/artifacts
            uv build
            cp dist/* /home/circleci/artifacts/
            

      - persist_to_workspace:
          name: persist to workspace
          root: /home/circleci/artifacts
          paths:
            - ./

  publish-github-release:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ~/artifacts
      - run:
          name: upgrade ghr to v0.15.0
          environment:
            GHR_VERSION: 0.15.0
          command: |
            GHR_URL=https://github.com/tcnksm/ghr/releases/download/v${GHR_VERSION}/ghr_v${GHR_VERSION}_linux_amd64.tar.gz
            wget "$GHR_URL" && \
              tar xzf ghr_v${GHR_VERSION}_linux_amd64.tar.gz && \
              mv ghr_v${GHR_VERSION}_linux_amd64/ghr /usr/bin/ghr && \
              rm -r ghr_v${GHR_VERSION}_linux_amd64.tar.gz ghr_v${GHR_VERSION}_linux_amd64/
      - run:
          name: "Publish Release on GitHub"
          command: |
            cd ~/project
            export VERSION=v$(date "+%Y%m%d_%H00")
            ghr \
              -n "${VERSION} ($(echo $CIRCLE_SHA1 | cut -c -7))" \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -delete \
              -generatenotes \
              ${VERSION} ~/artifacts/

workflows:
  ProjectWorkflow:
    jobs:
      - check
      - test
      - build-package:
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - publish-github-release:
          context: "github release context"
          filters:
            branches:
              only:
                - main